custom_css = ["css/style.css"]

# Meta Data for SEO

## Homepage
title = "pntfx"
titleSeparator = "-"
titleAddition = "Building Bridges between Mathematical Concepts"
description = "pntfx is a HOOU project."

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["doks.png"]
ogLocale = "en_US"
domainTLD = "doks.netlify.app"
titleHome = "Doks Theme"

## Twitter Cards
twitterSite = "@..."
twitterCreator = "@..."

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Doks"
schemaAuthor = "JPG and FNAG"
schemaAuthorTwitter = "https://twitter.com/..."
schemaAuthorLinkedIn = "https://www.linkedin.com/in/..."
schemaAuthorGitHub = "https://github.com/h-enk"
schemaLocale = "en-US"
schemaLogo = "pntfx.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "pnfx.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = ""
schemaLinkedIn = ""
schemaGitHub = "https://collaborating.tuhh.de/hoou-an-der-tuhh-projekte/pontifex/"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Footer
footer = "Powered by <a href=\"https://collaborating.tuhh.de/hoou-an-der-tuhh-projekte/pontifex\" target=\"_blank\">pntfx</a>. pntfx is a <a href=\"https://www.hoou.de\" target=\"_blank\">HOOU</a> project by <a href=\"https://math.fabian-gabel.de\" target=\"_blank\">Fabian Gabel</a> and <a href=\"https://www.jp-g.de\" target=\"_blank\">Julian Großmann</a> licensed under the <a href=\"mit-licence.org\" target=\"_blank\">MIT License</a>". The content on this webpage is licensed under a <a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\">Creative Commons Attribution 4.0 International License</a>"

# Feed
copyRight = "Copyright (c) 2020-2022 Pontifex"

# Alert
alert = false
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\">Check out Doks v0.2</a>"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitLab"
#repoHost = "Gitea"
docsRepo = "https://collaborating.tuhh.de/hoou-an-der-tuhh-projekte/pontifex"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = false
lastMod = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = false
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
