[[main]]
  name = "Network"
  url = "/docs/level1/"
  weight = 10

[[main]]
  name = "News"
  url = "/news/"
  weight = 20

[[main]]
  name = "Information"
  weight = 30
  identifier = "get-started"
  url = "/docs/chapter0/"

[[main]]
  name = "Hamburg Open Online University"
  weight = 30
  identifier = "hoou"
  url = "https://hoou.de"
  parent = "get-started"
  target="_blank"

[[main]]
  name = "About pntfx"
  weight = 60
  identifier = "aboutpntfx"
  url = "/news/aboutpntfx/"
  parent = "get-started"

[[social]]
  name = "GitLab"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-gitlab\"><path d=\"M22.65 14.39L12 22.13 1.35 14.39a.84.84 0 0 1-.3-.94l1.22-3.78 2.44-7.51A.42.42 0 0 1 4.82 2a.43.43 0 0 1 .58 0 .42.42 0 0 1 .11.18l2.44 7.49h8.1l2.44-7.51A.42.42 0 0 1 18.6 2a.43.43 0 0 1 .58 0 .42.42 0 0 1 .11.18l2.44 7.51L23 13.45a.84.84 0 0 1-.35.94z\"></path></svg>"
  url = "https://collaborating.tuhh.de/hoou-an-der-tuhh-projekte/pontifex"
  post = "v0.1.0"
  weight = 10
  target="_blank"

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/HOOU-TUHH/Pontifex-Hugo"
  post = "v0.1.0"
  weight = 10
  target="_blank"

[[footer]]
  name = "Feedback"
  url = "/feedback/"
  weight = 10

[[footer]]
  name = "Privacy"
  url = "/privacy-policy/"
  weight = 10

[[footer]]
  name = "Impressum"
  url = "/impressum/"
  weight = 10
