[[docs]]
  name = "Prologue"
  weight = 10
  identifier = "prologue"
  url = "/docs/prologue/"

[[docs]]
  name = "Help"
  weight = 60
  identifier = "help"
  url = "/docs/help/"

# [[docs]]
#   name = "Lorem"
#   weight = 70
#   identifier = "lorem"
#   url = "/docs/lorem/"

[[guide]]
  name = "Lorem"
  weight = 10
  identifier = "lorem"
  url = "/guide/lorem/"

[[tutorial]]
  name = "Lorem"
  weight = 10
  identifier = "lorem"
  url = "/tutorial/lorem/"

[[main]]
  name = "Network"
  url = "/docs/level1/"
# url = "/docs/1.0/prologue/introduction/"
  weight = 10

[[main]]
  name = "News"
  url = "/news/"
  weight = 20

[[main]]
  name = "Information"
  weight = 30
  identifier = "get-started"
  url = "/docs/chapter0/"

[[main]]
  name = "HOOU"
  weight = 30
  identifier = "hoou"
  url = "https://hoou.de"
  parent = "get-started"

[[main]]
  name = "TUHH Math"
  weight = 50
  identifier = "tuhhmath"
  url = "https://www.mat.tuhh.de"
  parent = "get-started"

[[main]]
  name = "About Pontifex"
  weight = 60
  identifier = "aboutpntfx"
  url = "/news/aboutpntfx/"
  parent = "get-started"

[[social]]
  name = "GitLab"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-gitlab\"><path d=\"M22.65 14.39L12 22.13 1.35 14.39a.84.84 0 0 1-.3-.94l1.22-3.78 2.44-7.51A.42.42 0 0 1 4.82 2a.43.43 0 0 1 .58 0 .42.42 0 0 1 .11.18l2.44 7.49h8.1l2.44-7.51A.42.42 0 0 1 18.6 2a.43.43 0 0 1 .58 0 .42.42 0 0 1 .11.18l2.44 7.51L23 13.45a.84.84 0 0 1-.35.94z\"></path></svg>"
  url = "https://www3-dev.tuhh.de/e-10/pontifex/404.html"
  post = "v0.1.0"
  weight = 10

[[footer]]
  name = "Privacy"
  url = "/privacy-policy/"
  weight = 10

