# based on  
# https://gohugo.io/hosting-and-deployment/hosting-on-github/
# https://github.com/h-enk/doks/blob/master/.github/workflows/node.js-ci.yml
# and https://getdoks.org/docs/how-to/hosting/deployment/
###############################################################################
# MIT License
# 
# Copyright (c) 2022 Fabian Gabel and Julian Großmann
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
###############################################################################

name: GitHub pages

on:
  push:
    branches:
      - master  # Set a branch to deploy
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out project
      uses: actions/checkout@v3
      
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10.7'
        
    - uses: nikeee/setup-pandoc@v1
      with:
        pandoc-version: '2.19.2' # The pandoc version to download (if necessary) and use.

    - name: Set up Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 18.9

    - name: Set baseurl
      run: 
        sed -i -e "s;baseurl.*;baseurl = \"/${{ github.event.repository.name }}//\";" config/production/config.toml

    - name: Build Pontifex
      run: bin/build_pontifex.sh

#    - name: Install dependencies
#      run: npm install
#
#    - name: Build production website
#      run: npm run build
          
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
