# based on  
# https://gohugo.io/hosting-and-deployment/hosting-on-github/
# https://github.com/h-enk/doks/blob/master/.github/workflows/node.js-ci.yml
# and https://getdoks.org/docs/how-to/hosting/deployment/

name: GitHub pages

on:
  push:
    branches:
      - master  # Set a branch to deploy
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out project
      uses: actions/checkout@v3
      
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - uses: nikeee/setup-pandoc@v1
      with:
        pandoc-version: '2.19.2' # The pandoc version to download (if necessary) and use.

    - name: Set up Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 18.9

    - name: Set baseurl
      run: 
        sed -i -e "s;baseurl.*;baseurl = \"/${{ github.event.repository.name }}//\";" config/production/config.toml
        sed -i -e "s;/js/pontifex-graph.js;${{ github.event.repository.name }}/js/pontifex-graph.js;" layouts/shortcodes/header1.html

    - name: Build Pontifex
      run: bin/build_pontifex.sh

#    - name: Install dependencies
#      run: npm install
#
#    - name: Build production website
#      run: npm run build
          
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
