# taken from https://gohugo.io/hosting-and-deployment/hosting-on-github/
# and https://github.com/h-enk/doks/blob/master/.github/workflows/node.js-ci.yml

name: github pages

on:
  push:
    branches:
      - master  # Set a branch to deploy
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out project
      uses: actions/checkout@v3
      
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - uses: nikeee/setup-pandoc@v1
      with:
        pandoc-version: '2.18' # The pandoc version to download (if necessary) and use.
    - run: echo "# Test" | pandoc -t html

    - name: Set up Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 18.5

    - name: Install dependencies
      run: npm install

    - name: Build production website
      run: npm run build
          
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
